FROM docker.n8n.io/n8nio/n8n:latest

ENV TZ=America/Sao_Paulo \
    N8N_BASIC_AUTH_ACTIVE=true \
    N8N_BASIC_AUTH_USER=admin \
    N8N_BASIC_AUTH_PASSWORD=admin \
    N8N_ENCRYPTION_KEY=mysecretkey \
    DB_TYPE=postgresdb \
    DB_POSTGRESDB_HOST=dpg-d0qv73p5pdvs73b03vv0-a \
    DB_POSTGRESDB_PORT=5432 \
    DB_POSTGRESDB_DATABASE=n8n_8m76 \
    DB_POSTGRESDB_USER=n8n_8m76_user \
    DB_POSTGRESDB_PASSWORD=dUT8oLog2cvSt0reyKDoRQgjI5WmSZRz \
    N8N_PORT=5678 \
    N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true

EXPOSE 5678

CMD ["n8n"]

